// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: td0.Ex0.proto

package td0;

public interface MyUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:td0.td0.MyUserProto.MyUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>uint32 year_of_birth = 2;</code>
   * @return The yearOfBirth.
   */
  int getYearOfBirth();
}
