// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lab1GRPC.proto

package MyLab1;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyLab1.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   * @return The reply.
   */
  String getReply();
  /**
   * <code>string reply = 1;</code>
   * @return The bytes for reply.
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
